version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - django-net
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django-app:
    build:
      context: .
    image: akj49/django-todo-app
    container_name: django-app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    networks:
      - django-net
    depends_on:
      - mysql
    command: sh -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 todo_project.wsgi"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build:
      context: ./nginx/
    image: akj49/django-nginx
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"
    networks:
      - django-net
    depends_on:
      - django-app
    restart: always

networks:
  django-net:

volumes:
  mysql-data:
