---
- name: Destroy ToDo App infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: todo-app-key
    key_path: ./todo-app-key
    region: ap-south-1
    instance_name: "todo-app"
    security_group_name: "todo-sg"

  tasks:

    - name: Gather EC2 instances with name tag "todo-app"
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ instance_name }}"
          instance-state-name: ["pending", "running", "stopping", "stopped"]
        region: "{{ region }}"
      register: ec2_info

    - name: Terminate EC2 instances
      when: ec2_info.instances | length > 0
      amazon.aws.ec2_instance:
        instance_ids: "{{ ec2_info.instances | map(attribute='instance_id') | list }}"
        region: "{{ region }}"
        state: absent
        wait: yes

    - name: Delete security group
      amazon.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        region: "{{ region }}"
        state: absent

    - name: Delete SSH key from AWS
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: absent

    - name: Delete private key file locally
      ansible.builtin.file:
        path: "{{ key_path }}"
        state: absent

    - name: Delete public key file locally
      ansible.builtin.file:
        path: "{{ key_path }}.pub"
        state: absent

    - name: Cleanup complete
      debug:
        msg: "Teardown complete. All resources have been removed."

